version: '3.17'
services:
  postgresql:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_docker
      - POSTGRES_USER=mainuser
      - POSTGRES_PASSWORD=mypassword